# Generated by Django 4.2.17 on 2025-03-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.profile')),
                ('own_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('household_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('household_members', models.IntegerField(default=1)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_elderly', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('employment_status', models.CharField(choices=[('Working', 'Working'), ('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired'), ('Disabled', 'Disabled')], max_length=20)),
                ('housing_status', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented'), ('Homeless', 'Homeless'), ('Shelter', 'Shelter'), ('Other', 'Other')], max_length=20)),
            ],
            bases=('account.profile',),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Public', 'Public'), ('Organisation', 'Organisation')], default='Public', max_length=256),
        ),
    ]
