# Generated by Django 4.2.17 on 2025-03-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_financialprofile_remove_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialProfile',
        ),
    ]
