# Generated by Django 4.2.17 on 2025-03-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_financialprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('household_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('household_members', models.IntegerField(default=1)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_elderly', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('employment_status', models.CharField(choices=[('Working', 'Working'), ('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired'), ('Disabled', 'Disabled')], max_length=20)),
                ('housing_status', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented'), ('Homeless', 'Homeless'), ('Shelter', 'Shelter'), ('Other', 'Other')], max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='account.profile')),
            ],
        ),
    ]
