# Generated by Django 4.2.17 on 2025-03-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_financialprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='needs_help',
            field=models.BooleanField(default=False),
        ),
    ]
