# Generated by Django 4.2.17 on 2025-03-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0004_fundraisercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
