# Generated by Django 4.2.17 on 2025-03-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0005_fundraiser_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='banner_image',
        ),
    ]
