# Generated by Django 4.2.17 on 2025-03-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_resource_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='deadline',
        ),
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resource.resource')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=20)),
            ],
            bases=('resource.resource',),
        ),
    ]
