# Generated by Django 4.2.17 on 2025-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_event_eventcategory_eventcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', to='service.eventcategory'),
        ),
    ]
