# Generated by Django 5.1.3 on 2024-12-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_resourcecategory_profile_is_dm_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='categories',
            field=models.ManyToManyField(related_name='discussions', to='home.discussioncategory'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='categories',
            field=models.ManyToManyField(related_name='resources', to='home.resourcecategory'),
        ),
    ]
