# Generated by Django 5.1.3 on 2024-12-14 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_resource_attachment_resource_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='max_income_gross',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='max_income_pc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='min_income_gross',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='min_income_pc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contributor', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_provider', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='services', to='home.servicecategory')),
            ],
        ),
    ]
