# Generated by Django 5.1.3 on 2025-01-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_service_contributor_remove_service_provider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
