# Generated by Django 5.1.3 on 2025-01-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='discussioncomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='discussioncomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='discussioncomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='author',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='resourcecomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='resourcecomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='resourcecomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='service',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='servicecomment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicecomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='servicecomment',
            name='parent',
        ),
        migrations.DeleteModel(
            name='DiscussionCategory',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='DiscussionComment',
        ),
        migrations.DeleteModel(
            name='ResourceCategory',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourceComment',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceComment',
        ),
    ]
